apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: devops-lab

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: sri0108/misinformation-backend:v1

          imagePullPolicy: Never

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: backend-config

            - secretRef:
                name: app-secret

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"

          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 40
            periodSeconds: 20