apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: devops-lab
type: Opaque
stringData:
  SECRET_KEY: "super-secret-key-change-in-production-12345"
  JWT_SECRET_KEY: "jwt-super-secret-key-change-in-production-67890"