apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}

data:
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  UPLOAD_FOLDER: {{ .Values.config.uploadFolder | quote }}
  REPORT_FOLDER: {{ .Values.config.reportFolder | quote }}
  TESSERACT_PATH: {{ .Values.config.tesseractPath | quote }}
  FLASK_ENV: {{ .Values.config.flaskEnv | quote }}
  FLASK_DEBUG: {{ .Values.config.flaskDebug | quote }}